# Generated by Django 2.2 on 2019-09-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190914_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Default/hqdefault.jpg', help_text='Kapak Fotoğrafı yükleyiniz.', null=True, upload_to='', verbose_name='Resim'),
        ),
    ]
