# Generated by Django 2.2 on 2019-09-21 08:13

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='yayin_taslak',
            field=models.CharField(choices=[(None, 'Lutfen Birini Seçiniz'), ('yayin', 'YAYIN'), ('taslak', 'TASLAK')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='Default/hqdefault.jpg', help_text='Kapak Fotoğrafı yükleyiniz.', null=True, upload_to=blog.models.upload_to, verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
