# Generated by Django 2.2 on 2019-09-24 10:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190924_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(blank=True, max_length=50, null=True, verbose_name='İsim')),
                ('soyisim', models.CharField(blank=True, max_length=50, null=True, verbose_name='Soyisim')),
                ('email', models.EmailField(blank=True, help_text='bu alanın girilmesi zorunlu.', max_length=254, verbose_name='Email')),
                ('icerik', ckeditor.fields.RichTextField(help_text='fikrinizi yazınız', max_length=1000, null=True, verbose_name='yorum')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Blog')),
            ],
            options={
                'verbose_name_plural': 'Yorumlar',
            },
        ),
    ]
