# Generated by Django 2.2 on 2019-10-07 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20191007_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favorite_blog', to='blog.Blog')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='favorite_blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
