# Generated by Django 2.2 on 2019-10-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_favoriteblog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteblog',
            options={'verbose_name_plural': 'Favorilere Eklenen Gönderiler'},
        ),
    ]
