# Generated by Django 2.2 on 2019-10-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('following', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'verbose_name_plural': 'Takipleşme Sistemi'},
        ),
    ]
